<?php
function clock_theme($existing, $type, $theme, $path) {
  return array('clock' =>           
           array(
            'variables' => array(
                'zone' => null,
                'currentDateTime' => null,
                'utcOffset' => null,
                'dayOfTheWeek' => null,
                'timeZoneName' => null,
                'currentFileTime' => null,
            ),
            'template' => 'clockTwig',
        )
    );
}
